In [2]:
import numpy as np
import math

In [47]:
# Part 1
# Given a map, identify whether the map is completely positive

def map():
    choi_matrix = [[1, 0, 0, 0, (-1), 0, 0, 0, (-1)],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [(-1), 0, 0, 0, 1, 0, 0, 0, (-1)],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [(-1), 0, 0, 0, (-1), 0, 0, 0, 1]]
    
    eigenvalues, eigenvectors = np.linalg.eig(choi_matrix)
    res = all(ele <= math.exp(-3) for ele in eigenvalues)
    if res:
        print(eigenvalues)
    print("The eigenvalues are:")   
    print(eigenvalues)

map()

The eigenvalues are:
[-1.  2.  2.  0.  0.  0.  0.  0.  0.]


In [49]:
# Part 2
# Given a modified map, identify the value of p for which the eigenvalues are non negative
# This will result in complete positivity

def map(p):
    choi_matrix = [[1, 0, 0, 0, (2*p-1), 0, 0, 0, (2*p-1)],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [(2*p-1), 0, 0, 0, 1, 0, 0, 0, (2*p-1)],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [(2*p-1), 0, 0, 0, (2*p-1), 0, 0, 0, 1]]
    
    eigenvalues, eigenvectors = np.linalg.eig(choi_matrix)
    res = all(ele <= math.exp(-3) for ele in eigenvalues)
    if res:
        print(eigenvalues)
    print("The eigenvalues are:")   
    print(eigenvalues)
    print('')
    print("The eigenvectors are:")
    print(eigenvectors)
    return eigenvalues, eigenvectors

# Increment the value of p in the range of 0 to 1 by 0.01 

def drange(start, stop, step):
    while start <= stop:
            yield start
            start += step
    
for i in drange(0, 1, 0.01):
    print(i)
    map(i)

0
The eigenvalues are:
[-1.  2.  2.  0.  0.  0.  0.  0.  0.]

The eigenvectors are:
[[ 0.57735027 -0.81649658  0.42755853  0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          1.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          1.
   0.          0.          0.        ]
 [ 0.57735027  0.40824829  0.38862863  0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   1.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          1.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          1.        ]
 [ 0.57735027  0.40824829 -0.81618716  0.          0.          0.
   0.     

The eigenvalues are:
[0.04 2.92 0.04 0.   0.   0.   0.   0.   0.  ]

The eigenvectors are:
[[-0.81649658  0.57735027 -0.11861405  0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          1.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          1.
   0.          0.          0.        ]
 [ 0.40824829  0.57735027  0.75891265  0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   1.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          1.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          1.        ]
 [ 0.40824829  0.57735027 -0.6402986   0.          0.          0.
   

In [65]:
# Identify whether all the vectors are linearly independent

def dot_product():

    for l in range(9):
        for m in range(9):
            if (eigenvectors[:,l]@eigenvectors[:,m])!= 0:
                if l != m:
                    if (eigenvectors[:,l]@eigenvectors[:,m]) > math.exp(-3):
                        print("")
                        print("Vectors:")
                        print(l, m)
                        print("")
                        print("Dot product value:")
                        print(eigenvectors[:,l]@eigenvectors[:,m])

In [63]:
# The minimum value at which all the eigenvalues are non negative is p = 0.25
# but eigenvectors are not linearly independent.
# For eigenvalues at p = 0.5 eigenvectors are linearly independent.

eigenvalues, eigenvectors = map(1/4)
dot_product()

The eigenvalues are:
[ 1.50000000e+00 -5.55111512e-17  1.50000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00]

The eigenvectors are:
[[ 0.81649658 -0.57735027  0.30959441  0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          1.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          1.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          1.
   0.          0.          0.        ]
 [-0.40824829 -0.57735027  0.49950661  0.          0.          0.
   0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   1.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          1.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.  

In [64]:
# The minimum value at which all the eigenvalues are non negative is p = 0.25
# but eigenvectors are not linearly independent.
# For eigenvalues at p = 0.5 eigenvectors are linearly independent.

eigenvalues, eigenvectors = map(1/2)
dot_product()

The eigenvalues are:
[1. 0. 0. 0. 1. 0. 0. 0. 1.]

The eigenvectors are:
[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [76]:
## Kraus operators are:

k1 = [[1, 0, 0],
      [0, 0, 0],
      [0, 0, 0]]

k2 = [[0, 0, 0],
      [0, 1, 0],
      [0, 0, 0]]

k3 = [[0, 0, 0],
      [0, 0, 0],
      [0, 0, 1]]

# Verify whether sum of transpose(k)*k is Identity matrix.

def identity_mat_chk():
    ver_matrix = np.matmul(k1, k1) + np.matmul(k2, k2) + np.matmul(k3, k3)
    print(" The result of verified matrix is: ")
    print(ver_matrix)
        
identity_mat_chk()

 The result of verified matrix is: 
[[1 0 0]
 [0 1 0]
 [0 0 1]]
